### ISSUE TITLE
RQ3: How to find Bellwether?

### ISSUE THREAD

**Issue by vivekaxl** [vivekaxl/Bellwether-Config#5]

**Comment by vivekaxl** [comment]
I can find good trends for sac and spear but not so much for sqlite and x264.

I think the reason is that the number of columns <<<< number of rows. 

Need to try with percent rather than training_coeff * # of columns.

**Comment by vivekaxl** [comment]
![sac_bw](https://user-images.githubusercontent.com/6147456/36284676-9265118e-1276-11e8-8802-1ed363c857f8.png)
![sqlite_bw](https://user-images.githubusercontent.com/6147456/36284677-9277741e-1276-11e8-804e-c24bca58ceac.png)
![spear_bw](https://user-images.githubusercontent.com/6147456/36284678-929182f0-1276-11e8-987d-cbe3db5e3d39.png)
![x264_bw](https://user-images.githubusercontent.com/6147456/36284679-92a3b1e6-1276-11e8-9302-c8a41397dfd0.png)

**Comment by vivekaxl** [comment]
SQLite -> does not show good results. We might want to change the way we select SQLite.

@rahlk Any ideas? All I can think of is a brute force?

**Comment by rahlk** [comment]
Which one's the bellwether?

**Comment by rahlk** [comment]
Btw, in spear, how can rank diff be 0.1 or 0.01?

**Comment by vivekaxl** [comment]
Bellwethers:
1. sac: sac_4 -> clearly visible
2. sqlite: sqlite_88
3. spear: spear_7 ->clearly visible
4. x264: x264_9 -> There can be more than one bell wether

![image](https://user-images.githubusercontent.com/6147456/36284811-29070d18-1277-11e8-8b60-1b83db9eefce.png)

**Comment by vivekaxl** [comment]
@rahlk 
> Btw, in spear, how can rank diff be 0.1 or 0.01?

Good catch -> the actual number is 0 ->I changed it to 0.01 so that it shows up on a log scale.

**Comment by rahlk** [comment]
But there is still a point in SPEAR less than 1, that can't be right?

**Comment by rahlk** [comment]
As for SQL, can we pick a subset of the datasets. Not randomly, but by doing a quick experiment?
We could look for projects what show a correlation between dependent variables.

**Comment by vivekaxl** [comment]
> But there is still a point in SPEAR less than 1, that can't be right?

why is it?

**Comment by rahlk** [comment]
> why is it?

Well ranks are integers, so are their differences, no?

**Comment by vivekaxl** [comment]
> Well ranks are integers, so are their differences, no?

but that rank difference can be 0

**Comment by vivekaxl** [comment]
### Results:

sqlite : 3.682 +- 4.647
spear : 0.099 +- 0.0
sac : 0.639 +- **27.884**
storm-obj2 : 0.0 +- 0.0
x264 : 1.511 +- 8.182


# Doesn't work:
storm-obj1 : 2.268 +- **48.616**

### Notes:
- The rank predicted by the bellwether found by the bellwether method in x264 is within the top 1.51% of the dataset.  
- This can also be interpreted as the distance to heaven, where the distance is normalized to the range of the dependent values.
